import { neon } from '@neondatabase/serverless';

let schemaPromise: Promise<void> | undefined;

export function getSql() {
  const databaseUrl = process.env.BARBEARIA_URL ?? process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error(
      'BARBEARIA_URL não está configurada. Conecte o banco Neon ao projeto da Vercel.',
    );
  }
  return neon(databaseUrl);
}

export async function ensureSchema() {
  if (schemaPromise) return schemaPromise;

  const sql = getSql();
  schemaPromise = (async () => {
    await sql`CREATE TABLE IF NOT EXISTS appointments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date TEXT NOT NULL,
      professional TEXT NOT NULL,
      payment TEXT NOT NULL,
      service TEXT NOT NULL,
      client TEXT NOT NULL DEFAULT 'Cliente',
      amount_cents INTEGER NOT NULL,
      time TEXT NOT NULL,
      created_at TEXT NOT NULL
    )`;
    await sql`CREATE TABLE IF NOT EXISTS beverage_products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      price_cents INTEGER NOT NULL,
      stock INTEGER NOT NULL DEFAULT 0
    )`;
    await sql`CREATE TABLE IF NOT EXISTS beverage_sales (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date TEXT NOT NULL,
      product_id INTEGER NOT NULL REFERENCES beverage_products(id),
      product_name TEXT NOT NULL,
      client TEXT NOT NULL DEFAULT 'Cliente',
      quantity INTEGER NOT NULL,
      unit_price_cents INTEGER NOT NULL,
      created_at TEXT NOT NULL
    )`;
    await sql`CREATE TABLE IF NOT EXISTS expenses (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date TEXT NOT NULL,
      description TEXT NOT NULL,
      category TEXT NOT NULL,
      payment TEXT NOT NULL,
      amount_cents INTEGER NOT NULL,
      created_at TEXT NOT NULL
    )`;
    await sql`CREATE TABLE IF NOT EXISTS monthly_cuts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      month TEXT NOT NULL,
      professional TEXT NOT NULL,
      payment TEXT NOT NULL,
      client TEXT NOT NULL,
      amount_cents INTEGER NOT NULL DEFAULT 0,
      cuts_total INTEGER NOT NULL DEFAULT 4,
      cuts_used INTEGER NOT NULL DEFAULT 1,
      start_date TEXT NOT NULL,
      last_cut_date TEXT NOT NULL,
      time TEXT NOT NULL,
      created_at TEXT NOT NULL
    )`;
    await sql`CREATE INDEX IF NOT EXISTS idx_appointments_date ON appointments (date)`;
    await sql`CREATE INDEX IF NOT EXISTS idx_beverage_sales_date ON beverage_sales (date)`;
    await sql`CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses (date)`;
    await sql`CREATE INDEX IF NOT EXISTS idx_monthly_cuts_month ON monthly_cuts (month)`;
  })().catch((error) => {
    schemaPromise = undefined;
    throw error;
  });

  return schemaPromise;
}
